branches:
  only:
    - "master"
    - "develop"
language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r tests/requirements.txt --use-mirrors
  - python setup.py build
  - python setup.py install
script: 
  - nosetests --exe -v
  - pylint --rcfile=pylint-rc.ini pyavrophonetic
